name: rnaseq-voila
channels:
        - plotly
        - bioconda
        - conda-forge
dependencies:
        - plotly>=4.14.3
        - matplotlib-base
        - pandas
        - ipywidgets
        - jupyterlab>=3.1
        - voila>=0.2.11
        - scikit-learn
