name: rnaseq-voila
channels:
        - plotly
        - bioconda
        - conda-forge
dependencies:
        - plotly=5.1.0
        - matplotlib-base
        - pandas
        - dominate=2.3.1
        - ipywidgets
        - jupyterlab>=3.1
        - voila>=0.2.11
        - scikit-learn
